ignore:
  # Base image npm packages (node:22.22.0-alpine3.23) - bundled with npm, not fixable via app dependencies
  - vulnerability: GHSA-83g3-92jg-28cx
    include-aliases: true
    reason: >-
      tar arbitrary file overwrite via symlink chain - base image tar 6.2.1/7.4.3,
      requires Node.js release with updated npm
  - vulnerability: GHSA-34x7-hfp2-rc4v
    include-aliases: true
    reason: >-
      tar arbitrary file overwrite - base image tar 6.2.1/7.4.3,
      requires Node.js release with updated npm
  - vulnerability: GHSA-r6q2-hw4h-h46w
    include-aliases: true
    reason: >-
      tar arbitrary file overwrite - base image tar 6.2.1/7.4.3,
      requires Node.js release with updated npm
  - vulnerability: GHSA-8qq5-rm4j-mr97
    include-aliases: true
    reason: >-
      tar arbitrary file overwrite - base image tar 6.2.1/7.4.3,
      requires Node.js release with updated npm

  # glob in built Docker image - transitive dep, no override available for this path
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: >-
      glob 10.4.5 ReDoS - transitive dependency in Docker image, override not possible for this dep path

  # Alpine base image CVEs (node:22.22.0-alpine3.23)
  - vulnerability: CVE-2025-60876
    package:
      type: apk
    reason: >-
      busybox wget CRLF injection - no fix in Alpine 3.23 yet. Simulator does not
      fetch attacker-controlled URLs.

output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
