ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: Fix available but specific version unknown for glob (GHSA enrichment may have failed)
output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
