ignore:
  # Base image npm packages (node:22.22.0-alpine3.23) - bundled in Node.js, not fixable via application dependencies
  - vulnerability: GHSA-83g3-92jg-28cx
    include-aliases: true
    reason: >-
      tar arbitrary file overwrite via symlink chain - bundled in Node.js base image at
      /usr/local/lib/node_modules/ (tar 6.2.1 and 7.4.3), requires Node.js release with updated npm

output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
