ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: Fix available but specific version unknown for glob (GHSA enrichment may have failed)
  # Alpine base image busybox vulnerabilities (node:22.21.1-alpine3.23)
  # Added 2026-01-13 - Review when Node.js releases updated Alpine image
  # These are in base image packages, not application code. Using apk upgrade
  # would break build reproducibility. Will be resolved when upstream Node.js
  # Docker image is rebuilt with patched Alpine packages.
  - vulnerability: CVE-2025-60876
    package:
      type: apk
    reason: "busybox wget CRLF injection - No fix in Alpine 3.23 yet (MR pending). EPSS <0.1%. Simulator does not fetch attacker-controlled URLs."
  - vulnerability: CVE-2025-46394
    package:
      type: apk
    reason: "busybox tar escape sequence hiding - Fixed in 1.37.0-r14, awaiting Node.js image rebuild. EPSS <0.1%. Simulator does not extract untrusted archives."
  - vulnerability: CVE-2024-58251
    package:
      type: apk
    reason: "busybox vulnerability - Fixed in 1.37.0-r14, awaiting Node.js image rebuild. EPSS <0.1%. Low severity, low risk in simulator context."
output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
