ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: Fix available but specific version unknown for glob (GHSA enrichment may have failed)
  - vulnerability: CVE-2025-60876
    package:
      type: apk
    reason: >-
      busybox wget CRLF injection - No fix in Alpine 3.23 yet (MR pending). EPSS <0.1%. Simulator does not fetch
      attacker-controlled URLs.
  - vulnerability: CVE-2025-46394
    package:
      type: apk
    reason: >-
      busybox tar escape sequence hiding - Fixed in 1.37.0-r14, awaiting Node.js image rebuild. EPSS <0.1%. Simulator
      does not extract untrusted archives.
  - vulnerability: CVE-2024-58251
    package:
      type: apk
    reason: >-
      busybox vulnerability - Fixed in 1.37.0-r14, awaiting Node.js image rebuild. EPSS <0.1%. Low severity, low risk in
      simulator context.
  - vulnerability: GHSA-34x7-hfp2-rc4v
    include-aliases: true
    reason: >-
      Base image npm package: tar - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-16 (high severity)
  - vulnerability: GHSA-73rr-hh4g-fpgx
    include-aliases: true
    reason: >-
      Base image npm package: diff - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-16 (low severity)
  - vulnerability: GHSA-r6q2-hw4h-h46w
    include-aliases: true
    reason: >-
      Base image npm package: tar - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-16 (high severity)
  - vulnerability: GHSA-8qq5-rm4j-mr97
    include-aliases: true
    reason: >-
      Base image npm package: tar - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-16 (high severity)
  # Alpine base image CVEs (node:22.21.1-alpine) - OS-level, unfixable at application level
  # Critical
  - vulnerability: CVE-2025-15467  # libcrypto3/libssl3
  # High
  - vulnerability: CVE-2025-69420  # libcrypto3/libssl3
  - vulnerability: CVE-2025-69421  # libcrypto3/libssl3
  - vulnerability: CVE-2025-69419  # libcrypto3/libssl3
  # Medium
  - vulnerability: CVE-2026-22796  # libcrypto3/libssl3
  - vulnerability: CVE-2025-66199  # libcrypto3/libssl3
  - vulnerability: CVE-2025-15468  # libcrypto3/libssl3
  - vulnerability: CVE-2026-22795  # libcrypto3/libssl3
  - vulnerability: CVE-2025-68160  # libcrypto3/libssl3
  - vulnerability: CVE-2025-11187  # libcrypto3/libssl3
  - vulnerability: CVE-2025-15469  # libcrypto3/libssl3
  - vulnerability: CVE-2025-69418  # libcrypto3/libssl3

  # Node.js binary CVEs - require newer Node.js release
  # Critical
  - vulnerability: CVE-2025-55130  # node 22.21.1
  # High
  - vulnerability: CVE-2025-59465  # node 22.21.1
  - vulnerability: CVE-2026-21637  # node 22.21.1
  - vulnerability: CVE-2025-55131  # node 22.21.1
  - vulnerability: CVE-2025-59466  # node 22.21.1
  # Medium
  - vulnerability: CVE-2025-55132  # node 22.21.1

output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
