{{- range $name, $customConfig := .Values.simulators }}
{{- $config := merge $customConfig $.Values.defaults }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-{{ $name }}
  labels:
    app: sim-{{ $name }}
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: sim-{{ $name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: sim-{{ $name }}
        release: {{ $.Release.Name }}
    spec:
      volumes:
      - name: jws-private-key
        secret:
          {{- if $config.config.schemeAdapter.secrets.sim_jws_priv_key_secret_name }} 
          secretName: {{ $config.config.schemeAdapter.secrets.sim_jws_priv_key_secret_name }}
          {{- else }}
          secretName: sim-{{ $name }}-jws-priv-key
          {{- end }}
      - name: jws-public-keys
        configMap:
          {{- if $config.config.schemeAdapter.secrets.sim_jws_pub_keys_map_name }} 
          name: {{ $config.config.schemeAdapter.secrets.sim_jws_pub_keys_map_name }}
          {{- else }}
          name: sim-jws-public-keys
          {{- end }}
      {{- if $config.config.schemeAdapter.secrets.sim_tls_secrets_name }} 
      - name: tls-secrets
        secret:
          secretName: {{ $config.config.schemeAdapter.secrets.sim_tls_secrets_name }}
      {{- end }}
      containers:
      - name: backend
        image: "{{ $config.config.simBackend.image.repository }}:{{ $config.config.simBackend.image.tag }}"
        imagePullPolicy: {{ $config.config.simBackend.image.pullPolicy }}
        ports:
          - name: simapi
            containerPort: 3000
            protocol: TCP
          - name: reportapi
            containerPort: 3002
            protocol: TCP
          - name: testapi
            containerPort: 3003
            protocol: TCP
        {{- if $config.config.simBackend.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
{{ $config.config.simBackend.readinessProbe | toYaml | indent 10 -}}
        {{- end }}
        {{- if $config.config.simBackend.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
{{ $config.config.simBackend.livenessProbe | toYaml | indent 10 -}}
        {{- end }}
        envFrom:
        - configMapRef:
            name: sim-{{ $name }}-backend
        resources:
{{ toYaml $config.config.simBackend.resources | indent 12 }}
      - name: scheme-adapter
        image: "{{ $config.config.schemeAdapter.image.repository }}:{{ $config.config.schemeAdapter.image.tag }}"
        imagePullPolicy: {{ $config.config.schemeAdapter.image.pullPolicy }}
        ports:
          - name: inboundapi
            containerPort: 4000
            protocol: TCP
          - name: outboundapi
            containerPort: 4001
            protocol: TCP
        {{- if $config.config.schemeAdapter.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: 4001
            scheme: HTTP
{{ $config.config.simBackend.readinessProbe | toYaml | indent 10 -}}
        {{- end }}
        {{- if $config.config.schemeAdapter.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: 4001
            scheme: HTTP
{{ $config.config.simBackend.livenessProbe | toYaml | indent 10 -}}
        {{- end }}
        volumeMounts:
        - name: jws-public-keys
          mountPath: {{ $config.config.schemeAdapter.env.JWS_VERIFICATION_KEYS_DIRECTORY }}
        - name: jws-private-key
          mountPath: "/jwsSigningKey/"
        {{- if $config.config.schemeAdapter.secrets.sim_tls_secrets_name }}
        - name: tls-secrets
          mountPath: "/secrets/"
        {{- end }}
        envFrom:
        - configMapRef:
            name: sim-{{ $name }}-scheme-adapter
          resources:
{{ toYaml $config.config.schemeAdapter.resources | indent 12 }}
      imagePullSecrets:
        - name: {{ $config.config.imagePullSecretName }}
    {{- with $config.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $config.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $config.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
{{- if $config.config.cache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-{{ $name }}-cache
  labels:
    app: {{ $name }}
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: sim-{{ $name }}-cache
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: sim-{{ $name }}-cache
        release: {{ $.Release.Name }}
    spec:
      containers:
      - name: cache
        image: "{{ $config.config.cache.image.repository }}:{{ $config.config.cache.image.tag }}"
        imagePullPolicy: {{ $config.config.cache.image.pullPolicy }}
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        {{- if $config.config.cache.livenessProbe.enabled }}
        livenessProbe:
{{ $config.config.simBackend.livenessProbe | toYaml | indent 10 -}}
          exec:
            command:
            - sh
            - -c
            - redis-cli ping {{ $config.config.cache.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if $config.config.cache.readinessProbe.enabled}}
        readinessProbe:
{{ $config.config.simBackend.readinessProbe | toYaml | indent 10 -}}
          exec:
            command:
            - sh
            - -c
            - redis-cli ping {{ $config.config.cache.readinessProbe.timeoutSeconds }}
        {{- end }}
        resources:
{{ toYaml $config.config.cache.resources | indent 12 }}
---
{{- end }}
{{ end }}
