#! /bin/bash

CURRENT_DATE=$(date)
for participantMSISDN in $(echo "${MSISDN_LIST}" | jq -c '.[]'); do
    echo "Calling Pathfinder with ${participantMSISDN}";
    MSISDN=$(echo "${participantMSISDN}" | jq -r '.MSISDN');
    DATA=$(echo "${participantMSISDN}" | jq -c '.data');
    curl --location --request PUT "${PATHFINDER_URL}/participants/MSISDN/${MSISDN}" \
    --header 'Content-Type: application/json' \
    --header "date: ${CURRENT_DATE}" \
    --header "fspiop-source: ${SIM_NAME}" \
    --data-raw "${DATA}";
done